server:
  port: 8761

# Eureka Server Configuration
eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000

# Management & Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, refresh
      base-path: /actuator
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: dev

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  config:
    activate:
      on-profile: prod

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
