
eureka:
  datacenter: default
  environment: dev
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh
      base-path: /actuator
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.blubugtech.bakery_eureka_server: INFO
    root: INFO

---
spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    com.blubugtech.bakery_eureka_server: DEBUG
