
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh,gateway
      base-path: /actuator
  endpoint:
    health:
      show-details: always

spring:
  data:
    redis:
      host: redis-gateway
      port: 6379
  cloud:
    gateway:
      default-filters:
        - RewritePath=(?<segment>.*[^/])/+$, $\{segment}
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: auth-service
              uri: lb://bakery-auth-service
              predicates:
                - Path=/api/auth/**,/api/users/**,/api/store/**
              filters:
                - AuthenticationFilter
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
            - id: product-service
              uri: lb://bakery-product-service
              predicates:
                - Path=/api/categories/**,/api/products/**,/api/inventory/**,/api/uploads/**,/api/site-config/**
              filters:
                - AuthenticationFilter
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
            - id: order-service
              uri: lb://bakery-order-service
              predicates:
                - Path=/api/orders/**
              filters:
                - AuthenticationFilter
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
            - id: payment-service
              uri: lb://bakery-payment-service
              predicates:
                - Path=/api/payments/**,/api/refunds/**,/api/transactions/**
              filters:
                - AuthenticationFilter
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
            - id: cart-service
              uri: lb://bakery-cart-service
              predicates:
                - Path=/api/carts/**,/api/cart-items/**
              filters:
                - AuthenticationFilter
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
            - id: notification-service
              uri: lb://bakery-notification-service
              predicates:
                - Path=/api/notifications/**
              filters:
                - AuthenticationFilter
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20


logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: INFO
    org.springframework.web.reactive: INFO
    reactor.ipc.netty: INFO
    reactor.netty: INFO
    root: INFO

---
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
