
product:
  inventory:
    low-stock-threshold: 10
    auto-disable-when-zero: true
  images:
    default-image: "default-product.jpg"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh
      base-path: /actuator
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.blubugtech.bakery_product_service: INFO
    org.springframework.web: INFO
    root: INFO

spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.blubugtech.common.event.*"

---
spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    com.blubugtech.bakery_product_service: DEBUG
    org.springframework.web: DEBUG
