
springdoc:
  swagger-ui:
    urls:
      - name: Auth Service
        url: /docs/auth
      - name: Cart Service
        url: /docs/cart
      - name: Product Service
        url: /docs/product
      - name: Order Service
        url: /docs/order
      - name: Payment Service
        url: /docs/payment
      - name: Notification Service
        url: /docs/notification

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh,gateway
      base-path: /actuator
  endpoint:
    health:
      show-details: always

spring:
  codec:
    max-in-memory-size: 55MB
  data:
    redis:
      host: redis-gateway
      port: 6379
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - RewritePath=(?<segment>.*[^/])/+$, $\{segment}
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: auth-service-openapi
              uri: lb://bakery-auth-service
              predicates:
                - Path=/docs/auth
              filters:
                - RewritePath=/docs/auth, /v3/api-docs
            - id: cart-service-openapi
              uri: lb://bakery-cart-service
              predicates:
                - Path=/docs/cart
              filters:
                - RewritePath=/docs/cart, /v3/api-docs
            - id: product-service-openapi
              uri: lb://bakery-product-service
              predicates:
                - Path=/docs/product
              filters:
                - RewritePath=/docs/product, /v3/api-docs
            - id: order-service-openapi
              uri: lb://bakery-order-service
              predicates:
                - Path=/docs/order
              filters:
                - RewritePath=/docs/order, /v3/api-docs
            - id: payment-service-openapi
              uri: lb://bakery-payment-service
              predicates:
                - Path=/docs/payment
              filters:
                - RewritePath=/docs/payment, /v3/api-docs
            - id: notification-service-openapi
              uri: lb://bakery-notification-service
              predicates:
                - Path=/docs/notification
              filters:
                - RewritePath=/docs/notification, /v3/api-docs
            - id: auth-service
              uri: lb://bakery-auth-service
              predicates:
                - Path=/api/auth/**,/api/users/**,/api/store/**
              filters:
                - AuthenticationFilter
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
            - id: product-service
              uri: lb://bakery-product-service
              predicates:
                - Path=/api/categories/**,/api/products/**,/api/inventory/**,/api/uploads/**,/api/storefront/**
              filters:
                - AuthenticationFilter
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
            - id: order-service
              uri: lb://bakery-order-service
              predicates:
                - Path=/api/orders/**
              filters:
                - AuthenticationFilter
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
            - id: payment-service
              uri: lb://bakery-payment-service
              predicates:
                - Path=/api/payments/**,/api/refunds/**,/api/transactions/**
              filters:
                - AuthenticationFilter
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
            - id: cart-service
              uri: lb://bakery-cart-service
              predicates:
                - Path=/api/carts/**,/api/cart-items/**
              filters:
                - AuthenticationFilter
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
            - id: notification-service
              uri: lb://bakery-notification-service
              predicates:
                - Path=/api/notifications/**
              filters:
                - AuthenticationFilter
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20


logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: INFO
    org.springframework.web.reactive: INFO
    reactor.ipc.netty: INFO
    reactor.netty: INFO
    root: INFO

---
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG

